services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mysongdb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
     - custom_network

volumes:
  postgres_data:

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.100.0/24
